// app/layout.tsx
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import SessionProviderWrapper from "./SessionProviderWrapper"
import Header from "./components/header"
import CartProvider from "./context/CartContext"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "E commerce",
  description: "Generated by Tainan",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <SessionProviderWrapper>
          <CartProvider>
            <Header />
            {children}
          </CartProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  )
}
